/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminPerfiles: typeof import('./src/components/admin/AdminPerfiles.vue')['default']
    AdminUsuarios: typeof import('./src/components/admin/AdminUsuarios.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    Asistencia: typeof import('./src/components/Asistencia.vue')['default']
    FormSeccion: typeof import('./src/components/rh/FormSeccion.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NominaAdmin: typeof import('./src/components/nomina/NominaAdmin.vue')['default']
    NominaDetalleDialog: typeof import('./src/components/nomina/NominaDetalleDialog.vue')['default']
    NominaEmpleado: typeof import('./src/components/nomina/NominaEmpleado.vue')['default']
    NominaPeriodoDetalle: typeof import('./src/components/nomina/NominaPeriodoDetalle.vue')['default']
    RHAsistencia: typeof import('./src/components/rh/RHAsistencia.vue')['default']
    RHPersonal: typeof import('./src/components/rh/RHPersonal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
