/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/nomina': RouteRecordInfo<'/admin/nomina', '/admin/nomina', Record<never, never>, Record<never, never>, '/admin/nomina/' | '/admin/nomina/[id]'>,
    '/admin/nomina/': RouteRecordInfo<'/admin/nomina/', '/admin/nomina', Record<never, never>, Record<never, never>>,
    '/admin/nomina/[id]': RouteRecordInfo<'/admin/nomina/[id]', '/admin/nomina/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/usuarios': RouteRecordInfo<'/admin/usuarios', '/admin/usuarios', Record<never, never>, Record<never, never>>,
    '/asistencia': RouteRecordInfo<'/asistencia', '/asistencia', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/nomina': RouteRecordInfo<'/nomina', '/nomina', Record<never, never>, Record<never, never>>,
    '/rh/asistencia': RouteRecordInfo<'/rh/asistencia', '/rh/asistencia', Record<never, never>, Record<never, never>>,
    '/rh/personal': RouteRecordInfo<'/rh/personal', '/rh/personal', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/nomina.vue': {
      routes: '/admin/nomina' | '/admin/nomina/' | '/admin/nomina/[id]'
      views: 'default'
    }
    'src/pages/admin/nomina/index.vue': {
      routes: '/admin/nomina/'
      views: never
    }
    'src/pages/admin/nomina/[id].vue': {
      routes: '/admin/nomina/[id]'
      views: never
    }
    'src/pages/admin/usuarios.vue': {
      routes: '/admin/usuarios'
      views: never
    }
    'src/pages/asistencia.vue': {
      routes: '/asistencia'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/nomina.vue': {
      routes: '/nomina'
      views: never
    }
    'src/pages/rh/asistencia.vue': {
      routes: '/rh/asistencia'
      views: never
    }
    'src/pages/rh/personal.vue': {
      routes: '/rh/personal'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
